# key? 32byte (256bit)
server:
  port: 8082

jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012

kakao:
  id: 748f5ec6acf376dbecc444759629df2c
  url: https://dapi.kakao.com/v2/local/search/keyword


spring:
  datasource:
    url: jdbc:mysql://semtle.catholic.ac.kr:3306/ataste?useUnicode=true&serverTimezone=Asia/Seoul
    username: mango
    password: my-secret-pw
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

# jdbc:mysql://127.0.0.1:3306/ataste?useUnicode=true&serverTimezone=Asia/Seoul
# jdbc:mysql://semtle.catholic.ac.kr:3306/ataste?useUnicode=true&serverTimezone=Asia/Seoul