cloud:
  aws:
    s3:
      bucket: ataste-bucket
    credentials: # 이거는 깃허브에 올리면 안된다/
      access-key: AKIAUY37HOPKXMML4XHI
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false