# key? 32byte (256bit)
server:
  port: 8082

jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012

kakao:
  id: 748f5ec6acf376dbecc444759629df2c
  url: https://dapi.kakao.com/v2/local/search/keyword


spring:
  datasource:
    url: jdbc:mysql://taste.suitestudy.com:3306/ataste?useUnicode=true&serverTimezone=Asia/Seoul
    username: mango
    password: my-secret-pw
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  # aws-s3 gitignore을 위해 따로 yml 생성
  profiles:
    include: aws


# multipart 설정
spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB

logging: # S3 에러 발생한거 지우기 위해
  file:
    name: app.log
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR

# jdbc:mysql://127.0.0.1:3306/ataste?useUnicode=true&serverTimezone=Asia/Seoul
# jdbc:mysql://taste.suitestudy.com:3306/ataste?useUnicode=true&serverTimezone=Asia/Seoul